<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Hangfire.InMemory"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing"/>
        <PackageReference Include="Shouldly"/>
        <PackageReference Include="Testcontainers.MongoDb"/>
        <PackageReference Include="xunit.v3"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\LlmUsageMonitor.WebApi\LlmUsageMonitor.WebApi.csproj"/>
    </ItemGroup>

</Project>
