#!/usr/bin/env bash
# Publishes the GitHub release of $TAG (vX.Y.Z or collector-vX.Y.Z) with the given assets, from the release workflow.
#   publish-release.sh <title> <asset>...
# - Notes generated by GitHub since the previous tag of the same series (a release skips the prereleases before it).
# - A tag with a suffix (-rc.1) is a prerelease; the server releases carry GitHub's "Latest", the collector ones never.
# - Re-run on an existing release: the assets are uploaded again (--clobber), the notes are kept.
set -euo pipefail

title=$1
shift

if [[ $TAG == collector-v* ]]; then
	prefix=collector-v
	latest=false
else
	prefix=v
	latest=true
fi
version=${TAG#"$prefix"}
prerelease=false
if [[ $version == *-* ]]; then
	prerelease=true
	latest=false
fi

if gh release view "$TAG" > /dev/null 2>&1; then
	echo "$TAG already published: uploading its assets again"
	gh release upload "$TAG" "$@" --clobber
	exit 0
fi

# The tags of the series, highest version first, a prerelease below its release (versionsort.suffix); the previous tag is
# the first one after $TAG.
previous=""
found=false
while read -r tag; do
	if [[ $found == false ]]; then
		[[ $tag == "$TAG" ]] && found=true
		continue
	fi
	[[ $prerelease == false && ${tag#"$prefix"} == *-* ]] && continue
	previous=$tag
	break
done < <(git -c versionsort.suffix=- tag --list "${prefix}[0-9]*" --sort=-v:refname)

arguments=(--title "$title" --generate-notes --latest="$latest" --verify-tag)
[[ -n $previous ]] && arguments+=(--notes-start-tag "$previous")
[[ $prerelease == true ]] && arguments+=(--prerelease)

echo "Publishing $TAG (previous: ${previous:-none}, prerelease: $prerelease, latest: $latest)"
gh release create "$TAG" "$@" "${arguments[@]}"
