<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <UserSecretsId>3f6c2b1e-8d4a-4c7e-9a51-2e7b0d6f4c93</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\LlmUsageMonitor.Api\LlmUsageMonitor.WebApi\LlmUsageMonitor.WebApi.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.JavaScript"/>
        <PackageReference Include="Aspire.Hosting.Keycloak"/>
        <PackageReference Include="Aspire.Hosting.MongoDB"/>
    </ItemGroup>

</Project>
